#!/bin/bash
# Install ixa-pipe-time
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${thisdir}/lib
wget  http://ixa2.si.ehu.es/~jibalari/jvntextpro-2.0.jar
cd ${thisdir}
git clone https://github.com/PaulHuygen/install-to-project-repo.git
python install-to-project-repo/install-to-project-repo.py 
mvn clean install
mv target/ixa.pipe.jar .
